### ISSUE TITLE
[Suggestion] Adding quarter and time left to the text of the tweet

### ISSUE THREAD

**Issue by shatayu** [guga31bb/fourth_calculator#6]
The time and quarter left in the game is a very important part of going for it on 4th down. For example, at the 2 yard line one would normally go for it, but if it's at the end of the half then perhaps kicking would become a better option (see the Colts vs. Bills Wildcard 2020 game for reference). This information is unavailable without looking at the screenshot, which is a shame.

**Comment by guga31bb** [comment]
Leaving it in the screenshot due to character limits in the tweets
